#Reference : https://registry.hub.docker.com/r/linuxserver/mariadb

version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - MYSQL_ROOT_PASSWORD=newrootpassword # pragma: allowlist secret
      - MYSQL_DATABASE= baseball
      - MYSQL_USER= root
      - MYSQL_PASSWORD= newrootpassword # pragma: allowlist secret
    volumes:
      - db:/config
    ports:
      - 8000:3306
    restart: unless-stopped
#  python_sql_service:
#    container_name: python_sql
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: python_sql_service
#    environment:
#      PORT: "8080"
#    volumes:
#      -
volumes:
  db:
